### ISSUE TITLE
Error while updating tailwindcss from v1.2 to 1.7

### ISSUE THREAD

**Issue by iaminamcom** [mhanberg/jekyll-tailwind-starter#15]
Hi. I can't use latest version of tailwindcss. When I do `npm update` run `bin/start`  I get following error. I think error is with the postcss plugin of jekyll. 

```
internal/modules/cjs/loader.js:796
    throw err;
    ^

Error: Cannot find module 'tailwindcss'
Require stack:
- /home/inam/web/jekyll-tw/postcss.config.js
- /home/linuxbrew/.linuxbrew/lib/ruby/gems/2.6.0/gems/jekyll-postcss-0.4.0/bin/postcss
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/inam/web/jekyll-tw/postcss.config.js:6:5)
    at Module._compile (internal/modules/cjs/loader.js:955:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:991:10)
    at Module.load (internal/modules/cjs/loader.js:811:32)
    at Function.Module._load (internal/modules/cjs/loader.js:723:14)
    at Module.require (internal/modules/cjs/loader.js:848:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/inam/web/jekyll-tw/postcss.config.js',
    '/home/linuxbrew/.linuxbrew/lib/ruby/gems/2.6.0/gems/jekyll-postcss-0.4.0/bin/postcss'
  ]
}
...
```
You created jekyll-postcss and can you make it working with the latest release?

**Comment by mhanberg** [comment]
Is this still a problem? i'm not sure this would be a bug with jekyll-postcss. if it says it can't find tailwind, that is probably a node/npm problem.

**Comment by iaminamcom** [comment]
Hi, never tried again.
